version: "2"
services:
  app:
    container_name: blog-app
    build: server/
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    volumes:
      - ./server/app:/code/app
      - .env:/code/app/.env
    working_dir: /code/app
    environment:
      TZ: "Asia/Tokyo"
  postgres:
    image: postgres:12.11
    container_name: blog-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
