version: "2"
services:
  app:
    container_name: blog-app
    build: .
    ports:
      - "80:80"
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    volumes:
      - ./app:/code/app
    environment:
      TZ: "Asia/Tokyo"
  postgres:
    image: postgres:12.11
    container_name: blog-db
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
