version: "2"
services:
  # app:
  #   container_name: ${APPLICATION_HOST}
  #   build: front/
  #   ports:
  #     - "${APPLICATION_PORT}:${APPLICATION_PORT}"
  #   restart: always
  #   volumes:
  #     - ./front/app:/code/app
  #     - .env:/code/app/.env
  #   command: sh -c "npm run dev"
  #   working_dir: /code/app
  #   environment:
  #     TZ: "Asia/Tokyo"
  server:
    container_name: ${SERVER_HOST}
    build: server/
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    volumes:
      - ./server/app:/code/app
      - .env:/code/app/.env
    working_dir: /code/app
    environment:
      TZ: "Asia/Tokyo"
  postgres:
    image: postgres:12.11
    container_name: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
